name: production

on:
  push:
    branches:
      - main

env:
  SERVER: ubuntu@42.193.192.55
  REPOSITORY: ccr.ccs.tencentyun.com
  IMAGE: ccr.ccs.tencentyun.com/xiejiapeng/${{ github.event.repository.name }}:production
  CONTAINER: ${{ github.event.repository.name }}.production

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout To Main
        uses: actions/checkout@v4

      - name: Login to docker repository
        run: |
          docker login ${{ env.REPOSITORY }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        run: |
          docker build -t ${{ env.IMAGE }} --build-arg env=${{ env.ENV }} --build-arg target=${{ env.TARGET }} .
          docker push ${{ env.IMAGE }}

      - name: Create private key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key

      - name: Connect remote server and run container
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private.key ${{ env.SERVER }} << EOF
            sudo docker login ${{ env.REPOSITORY }} -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            sudo docker pull ${{ env.IMAGE }}
            sudo docker stop ${{ env.CONTAINER }}
            sudo docker rm ${{ env.CONTAINER }} -f
            sudo docker run -d -p 3000:3000 --name ${{ env.CONTAINER }} ${{ env.IMAGE }}
            sudo docker container prune -f
            sudo docker image prune -a -f
          EOF


