name: production

on:
  push:
    branches:
      - main

env:
  SERVER: ubuntu@42.193.192.55
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/private:xiejiapeng.production
  CONTAINER: xiejiapeng.production

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout To Main
        uses: actions/checkout@v3

      - name: Login To Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build And Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Create Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key

      - name: Connect Remote Server And Run Container
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private.key ${{ env.SERVER }} << EOF
            sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
            sudo docker pull ${{ env.IMAGE }}
            sudo docker stop ${{ env.CONTAINER }}
            sudo docker rm ${{ env.CONTAINER }} -f
            sudo docker run -d -p 3000:3000 --name ${{ env.CONTAINER }} ${{ env.IMAGE }}
            sudo docker container prune -f
            sudo docker image prune -a -f
          EOF
